#!/bin/bash

# creating the new build
ng build --base-href "https://Zaqttack.github.io/test-angular-app"

# copying over some files and creating the gitHub pages CNAME
cd dist/test-app && cp index.html 404.html && echo "http://test.zaquariah.dev" > CNAME

# returning back to the src folder and deploying the built app
cd ../..
npx angular-cli-ghpages --dir=dist/test-app
